-- MySQL Script generated by MySQL Workbench
-- Thu Feb 29 23:03:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `success` DEFAULT CHARACTER SET utf8mb3 ;
USE `success` ;

-- -----------------------------------------------------
-- Table `success`.`Parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `success`.`Parent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `E-Mail_UNIQUE` (`e_mail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `success`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `success`.`Student` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Graduation` VARCHAR(45) NOT NULL,
  `Parent_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Student_Parent_idx` (`Parent_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Parent`
    FOREIGN KEY (`Parent_Id`)
    REFERENCES `success`.`Parent` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `success`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `success`.`Courses` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Student_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `fk_Courses_Student1_idx` (`Student_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Student1`
    FOREIGN KEY (`Student_Id`)
    REFERENCES `success`.`Student` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `success`.`Course_Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `success`.`Course_Results` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Course` VARCHAR(45) NULL DEFAULT NULL,
  `Course_Id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `TrueAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `FalseAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `EmptyAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `Result` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  INDEX `course_results_ibfk_1` (`Course_Id` ASC) VISIBLE,
  CONSTRAINT `course_results_ibfk_1`
    FOREIGN KEY (`Course_Id`)
    REFERENCES `success`.`Courses` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `success`.`Exam_Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `success`.`Exam_Results` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Student_Id` INT NOT NULL,
  `TrueAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `FalseAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `EmptyAnswer` VARCHAR(45) NULL DEFAULT NULL,
  `Result` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Exam Results_Student1_idx` (`Student_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Exam Results_Student1`
    FOREIGN KEY (`Student_Id`)
    REFERENCES `success`.`Student` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
